name: Auto Update Milford Parents Helper

on:
  push:
    branches: [ main ]          # run on any change to main
  schedule:
    - cron: '0 11 * * *'        # ~7:00 AM ET daily
  workflow_dispatch: {}          # manual "Run workflow" button

permissions:
  contents: write                # <-- lets the workflow commit & push

jobs:
  update-stub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update timestamps in sample_data.json (stub)
        shell: bash
        run: |
          python - <<'PY'
          import json, datetime
          path = "sample_data.json"
          with open(path, "r") as f:
              data = json.load(f)
          now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
          data["generated_at"] = now
          for key in ["this_week","today","actionables","changes","activities","quinn_resources"]:
              for item in data.get(key, []):
                  item["crawled_at"] = now
          with open(path, "w") as f:
              json.dump(data, f, indent=2)
          PY

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sample_data.json
          git commit -m "Auto-update stub timestamps [skip ci]" || echo "No changes to commit"
          git push
